### ISSUE TITLE
Cosmos db support

### ISSUE THREAD

**Issue by AidanRRR** [dlmelendez/identityazuretable#26]
Is it normal that it can't connect to cosmos (table storage)?
Gives me connection errors. Is this normal and should I just connect wit the normal storage table or am I setting it up badly?

**Comment by dlmelendez** [comment]
@AidanRRR which package are you using ElCamino.AspNetCore.Identity.AzureTable  or ElCamino.AspNet.Identity.AzureTable ? and what version ?

**Comment by dlmelendez** [comment]
I see what the problem is... the premium table storage (cosmos) has a different version of the storage library to connect. As a result, this project doesn't support premium table storage at this time. However, take a look at my other cosmos db compatible identity project, https://github.com/dlmelendez/identitycoredocumentdb or use a standard table storage account with this project. Thanks, Dave

**Comment by AidanRRR** [comment]
Thank you for having a look dave, appreciated.
Didn't knew you had another cosmos db project! Cool!
