### ISSUE TITLE
Works identityazuretable with AspNetCore WebAPI?

### ISSUE THREAD

**Issue by CodeEXc** [dlmelendez/identityazuretable#27]
Hi,

I want create a AspNet Core Web API application with a JWT Bearer Authentication for a mobile solotion.
Does anyone have experience creating an authentication API with Azue Tables?

Many thanks!
CodeEXc

**Comment by dlmelendez** [comment]
You bet Azure Tables will work in this scenario. However, you need to check out and use IdentityServer4 with AspNetCore.Identity.  Check out this quickstart on IdentityServer4 and just plug in the Azure Tables Identity provider instead of using the EntityFramework provider. https://github.com/IdentityServer/IdentityServer4.Samples/tree/2.0.0/Quickstarts/6_AspNetIdentity . Hope this gets you pointed in the right direction.
-Dave
