### ISSUE TITLE
Extending the basekeyhelper class to support tenant id

### ISSUE THREAD

**Issue by schillma** [dlmelendez/identityazuretable#29]
@dlmelendez, I read the "Feature Request to support Multi-tenancy w/ change to Partition Key" post.  You mention a plan to extend the basekeyhelper class. Did you complete this change? If so, how would you extend it to support putting a tenant id in the partition key?

Thanks for considering my request,
Mark

**Comment by dlmelendez** [comment]
@schillma, I did consider refactoring the basekeyhelper class but decided against it because it got pretty messy especially from a data migration path perspective. The easiest way to implement a multi-tenant environment would to leverage the table naming prefix for each tenant. Hopefully, this approach works for you.
-Dave

**Comment by schillma** [comment]
@dlmelendez , Thanks for your recommendation. Mark
