### ISSUE TITLE
How to make the storageConnectionString an env variable?

### ISSUE THREAD

**Issue by ClydeDz** [dlmelendez/identityazuretable#33]
Hey David,
     
I was following [this guide](https://dlmelendez.github.io/identityazuretable/#/walkthrough) to connect my app with table storage and it all works fine. 

However, I had a question - the connection string of the table storage need to be specified like this according to the documentation: `<elcaminoIdentityConfiguration tablePrefix="" storageConnectionString="UseDevelopmentStorage=true" />` but when I want to deploy this app to the cloud, lets say Azure, how would I make this as an environment variable (for Azure, an Application Setting/Connection String)? 

If this was a key-value pair in the `<appSettings>` section, it can easily made as a env variable in the hosting provider. Likewise the connection string in the `<connectionStrings>` section.  Keen to hear your thoughts!

Thanks,
Clyde

**Comment by dlmelendez** [comment]
This is related to #8 . If there is one thing I never should have implemented in this project, it is this typed configuration. Note, this is completely fixed in the .Net Core (most current release) of the package.
It isn't too hard to work around in this version either. Change:`public ApplicationDbContext() : base()
{}`
to 
`public ApplicationDbContext(IdentityConfiguration config): base(config){}`
Pull your configuration values into the IdentityConfiguration config instance and you are good to go. This way, you are free to store the values however you like.
-Dave

**Comment by ClydeDz** [comment]
Hey David, 

Thanks for your prompt reply. Yes, that solves the problem indeed. 

Thanks,
Clyde
