### ISSUE TITLE
Save config values in ServiceConfiguration.cscfg

### ISSUE THREAD

**Issue by jennet** [dlmelendez/identityazuretable#8]
My app settings go in ServiceConfiguration.XXXX.cscfg for my various cloud deployments, is there a way of overwriting the config settings so I can pass in my own IdentityConfiguration? (rather than it pulling values from a configSection of the Web.Config)

**Comment by jennet** [comment]
Hang on... I think I've just found the method to do just that....

**Comment by jennet** [comment]
In case anyone else stumbles across this, I created a new class inheriting from IdentityConfiguration in my IdentityModels file and set the values by grabbing them out of the ServiceConfiguration.cscfg file.
I then passed this in when creating an ApplicationDbContext

**Comment by dlmelendez** [comment]
Hi @jennet,
I kind of gave up on accommodating N number of configuration patterns just because there are so many different ways to approach it. Either taking your approach to inherit IdentityConfiguration or simply reading the config to populate an instance of the IdentityConfiguration class works just fine. Glad you got it working!
Thanks,
Dave
